##若物品较多，可手动续写配置
物品种类数: 10
#物品 "ID:DAMAGE"
第[1]种: "0:0"
第[2]种: "0:0"
第[3]种: "0:0"
第[4]种: "0:0"
第[5]种: "0:0"
第[6]种: "0:0"
第[7]种: "0:0"
第[8]种: "0:0"
第[9]种: "0:0"
第[10]种: "0:0"
#物品数量
第{1}种: 0
第{2}种: 0
第{3}种: 0
第{4}种: 0
第{5}种: 0
第{6}种: 0
第{7}种: 0
第{8}种: 0
第{9}种: 0
第{10}种: 0
#领取奖励后底部显示的提示语
提示语: Bear Cabbage is the cutest!

